# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'task_dialog_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(415, 255)
        self.formLayoutWidget = QtWidgets.QWidget(Dialog)
        self.formLayoutWidget.setGeometry(QtCore.QRect(10, 10, 398, 191))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.task_name_label_2 = QtWidgets.QLabel(self.formLayoutWidget)
        self.task_name_label_2.setStyleSheet("QLabel {\n"
"font: 14pt \"Comic Sans MS\";\n"
"}")
        self.task_name_label_2.setObjectName("task_name_label_2")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.task_name_label_2)
        self.task_name_le = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.task_name_le.setObjectName("task_name_le")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.task_name_le)
        self.deadline_label = QtWidgets.QLabel(self.formLayoutWidget)
        self.deadline_label.setStyleSheet("QLabel {\n"
"font: 14pt \"Comic Sans MS\";\n"
"}")
        self.deadline_label.setObjectName("deadline_label")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.deadline_label)
        self.deadline_time = QtWidgets.QDateTimeEdit(self.formLayoutWidget)
        self.deadline_time.setCurrentSection(QtWidgets.QDateTimeEdit.DaySection)
        self.deadline_time.setCalendarPopup(True)
        self.deadline_time.setObjectName("deadline_time")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.deadline_time)
        self.give_time_label = QtWidgets.QLabel(self.formLayoutWidget)
        self.give_time_label.setStyleSheet("QLabel {\n"
"font: 14pt \"Comic Sans MS\";\n"
"}")
        self.give_time_label.setObjectName("give_time_label")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.give_time_label)
        self.give_time_label_3 = QtWidgets.QLabel(self.formLayoutWidget)
        self.give_time_label_3.setStyleSheet("QLabel {\n"
"font: 14pt \"Comic Sans MS\";\n"
"}")
        self.give_time_label_3.setObjectName("give_time_label_3")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.give_time_label_3)
        self.info_tb = QtWidgets.QTextBrowser(self.formLayoutWidget)
        self.info_tb.setReadOnly(False)
        self.info_tb.setObjectName("info_tb")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.info_tb)
        self.give_time = QtWidgets.QDateTimeEdit(self.formLayoutWidget)
        self.give_time.setCurrentSection(QtWidgets.QDateTimeEdit.DaySection)
        self.give_time.setCalendarPopup(True)
        self.give_time.setObjectName("give_time")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.give_time)
        self.ok_btn = QtWidgets.QPushButton(Dialog)
        self.ok_btn.setGeometry(QtCore.QRect(10, 210, 111, 41))
        self.ok_btn.setStyleSheet("QPushButton {\n"
"background-color: rgb(85, 170, 0);\n"
"border-radius: 20px;\n"
"font: 14pt \"Comic Sans MS\";\n"
"border: 1px solid black;\n"
"}")
        self.ok_btn.setObjectName("ok_btn")
        self.cancel_btn = QtWidgets.QPushButton(Dialog)
        self.cancel_btn.setGeometry(QtCore.QRect(130, 210, 121, 41))
        self.cancel_btn.setStyleSheet("QPushButton {\n"
"background-color: rgba(255, 0, 0);\n"
"border-radius: 20px;\n"
"font: 14pt \"Comic Sans MS\";\n"
"border: 1px solid black\n"
"}")
        self.cancel_btn.setObjectName("cancel_btn")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.task_name_label_2.setText(_translate("Dialog", "Задание"))
        self.deadline_label.setText(_translate("Dialog", "Срок сдачи"))
        self.deadline_time.setDisplayFormat(_translate("Dialog", "dd.MM HH:mm"))
        self.give_time_label.setText(_translate("Dialog", "Время сдачи"))
        self.give_time_label_3.setText(_translate("Dialog", "Информация"))
        self.info_tb.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.give_time.setDisplayFormat(_translate("Dialog", "dd.MM HH:mm"))
        self.ok_btn.setText(_translate("Dialog", "Готово"))
        self.cancel_btn.setText(_translate("Dialog", "Отмена"))
