# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'task_dialog_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 350)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        Dialog.setMinimumSize(QtCore.QSize(400, 350))
        Dialog.setStyleSheet("QDialog{\n"
"background-color: rgb(254, 254, 254);\n"
"}\n"
"/* Панель заголовка */\n"
"TitleBar {\n"
"    background-color: rgb(32, 178, 170);\n"
"}\n"
"/* Минимизировать кнопку `Максимальное выключение` Общий фон по умолчанию */\n"
"#buttonMinimum, #buttonMaximum, #buttonClose, #buttonConnect {\n"
"    border: none;\n"
"    background-color: rgb(32, 178, 170);\n"
"    color: white;\n"
"}\n"
"/* Зависание */\n"
"#buttonMinimum:hover,#buttonMaximum:hover, #buttonConnect:hover {\n"
"    color: rgb(32, 178, 170);\n"
"    background-color: rgb(41, 229, 217);\n"
"}\n"
"#buttonClose:hover {\n"
"    color: rgb(32, 178, 170);\n"
"    background-color: rgb(41, 229, 217);\n"
"}\n"
"/* Мышь удерживать */\n"
"#buttonMinimum:pressed,#buttonMaximum:pressed {\n"
"    background-color: rgb(44, 125, 144);\n"
"}\n"
"#buttonClose:pressed {\n"
"    color: white;\n"
"    background-color: rgb(161, 73, 92);\n"
"}")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.header = TitleBar(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.header.sizePolicy().hasHeightForWidth())
        self.header.setSizePolicy(sizePolicy)
        self.header.setMinimumSize(QtCore.QSize(0, 30))
        self.header.setObjectName("header")
        self.horizontalLayout_2.addWidget(self.header)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setContentsMargins(9, 9, 9, 9)
        self.verticalLayout.setSpacing(5)
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setFieldGrowthPolicy(QtWidgets.QFormLayout.ExpandingFieldsGrow)
        self.formLayout.setObjectName("formLayout")
        self.subject_label = QtWidgets.QLabel(Dialog)
        self.subject_label.setStyleSheet("QLabel{\n"
"font: 57 10pt \"IBM Plex Sans\";\n"
"}")
        self.subject_label.setObjectName("subject_label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.subject_label)
        self.subjects_cb = QtWidgets.QComboBox(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.subjects_cb.sizePolicy().hasHeightForWidth())
        self.subjects_cb.setSizePolicy(sizePolicy)
        self.subjects_cb.setObjectName("subjects_cb")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.subjects_cb)
        self.task_label = QtWidgets.QLabel(Dialog)
        self.task_label.setStyleSheet("QLabel{\n"
"font: 57 10pt \"IBM Plex Sans\";\n"
"}")
        self.task_label.setObjectName("task_label")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.task_label)
        self.task_tb = QtWidgets.QTextBrowser(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.task_tb.sizePolicy().hasHeightForWidth())
        self.task_tb.setSizePolicy(sizePolicy)
        self.task_tb.setReadOnly(False)
        self.task_tb.setObjectName("task_tb")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.task_tb)
        self.deadline_label = QtWidgets.QLabel(Dialog)
        self.deadline_label.setStyleSheet("QLabel{\n"
"font: 57 10pt \"IBM Plex Sans\";\n"
"}")
        self.deadline_label.setObjectName("deadline_label")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.deadline_label)
        self.deadline_time = QtWidgets.QDateTimeEdit(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.deadline_time.sizePolicy().hasHeightForWidth())
        self.deadline_time.setSizePolicy(sizePolicy)
        self.deadline_time.setCurrentSection(QtWidgets.QDateTimeEdit.DaySection)
        self.deadline_time.setCalendarPopup(True)
        self.deadline_time.setObjectName("deadline_time")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.deadline_time)
        self.delivery_label = QtWidgets.QLabel(Dialog)
        self.delivery_label.setStyleSheet("QLabel{\n"
"font: 57 10pt \"IBM Plex Sans\";\n"
"}")
        self.delivery_label.setObjectName("delivery_label")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.delivery_label)
        self.delivery_time = QtWidgets.QDateTimeEdit(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.delivery_time.sizePolicy().hasHeightForWidth())
        self.delivery_time.setSizePolicy(sizePolicy)
        self.delivery_time.setCalendarPopup(True)
        self.delivery_time.setObjectName("delivery_time")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.delivery_time)
        self.link_label = QtWidgets.QLabel(Dialog)
        self.link_label.setStyleSheet("QLabel{\n"
"font: 57 10pt \"IBM Plex Sans\";\n"
"}")
        self.link_label.setObjectName("link_label")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.link_label)
        self.link_le = QtWidgets.QLineEdit(Dialog)
        self.link_le.setInputMethodHints(QtCore.Qt.ImhUrlCharactersOnly)
        self.link_le.setObjectName("link_le")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.link_le)
        self.verticalLayout.addLayout(self.formLayout)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.ok_btn = QtWidgets.QPushButton(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ok_btn.sizePolicy().hasHeightForWidth())
        self.ok_btn.setSizePolicy(sizePolicy)
        self.ok_btn.setMinimumSize(QtCore.QSize(101, 41))
        self.ok_btn.setMaximumSize(QtCore.QSize(151, 41))
        self.ok_btn.setStyleSheet("QPushButton {\n"
"background-color: rgb(71, 118, 93);\n"
"color: rgb(254, 254, 254);\n"
"border-radius: 20px;\n"
"font: 57 14pt \"IBM Plex Sans\";\n"
"}")
        self.ok_btn.setObjectName("ok_btn")
        self.horizontalLayout.addWidget(self.ok_btn)
        self.open_link_btn = QtWidgets.QPushButton(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.open_link_btn.sizePolicy().hasHeightForWidth())
        self.open_link_btn.setSizePolicy(sizePolicy)
        self.open_link_btn.setMinimumSize(QtCore.QSize(161, 41))
        self.open_link_btn.setMaximumSize(QtCore.QSize(201, 41))
        self.open_link_btn.setStyleSheet("QPushButton {\n"
"font: 57 14pt \"IBM Plex Sans\";\n"
"background-color: rgb(61, 79, 69);\n"
"color: rgb(254, 254, 254);\n"
"border-radius: 20px;\n"
"}")
        self.open_link_btn.setObjectName("open_link_btn")
        self.horizontalLayout.addWidget(self.open_link_btn)
        self.cancel_btn = QtWidgets.QPushButton(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cancel_btn.sizePolicy().hasHeightForWidth())
        self.cancel_btn.setSizePolicy(sizePolicy)
        self.cancel_btn.setMinimumSize(QtCore.QSize(101, 41))
        self.cancel_btn.setMaximumSize(QtCore.QSize(151, 41))
        self.cancel_btn.setStyleSheet("QPushButton {\n"
"background-color: rgb(136, 89, 84);\n"
"color: rgb(254, 254, 254);\n"
"border-radius: 20px;\n"
"font: 57 14pt \"IBM Plex Sans\";\n"
"}")
        self.cancel_btn.setObjectName("cancel_btn")
        self.horizontalLayout.addWidget(self.cancel_btn)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "AREA - Задание"))
        self.subject_label.setText(_translate("Dialog", "Предмет"))
        self.task_label.setText(_translate("Dialog", "Задание"))
        self.task_tb.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.deadline_label.setText(_translate("Dialog", "Срок сдачи"))
        self.deadline_time.setDisplayFormat(_translate("Dialog", "dd.MM HH:mm"))
        self.delivery_label.setText(_translate("Dialog", "Дата сдачи"))
        self.delivery_time.setDisplayFormat(_translate("Dialog", "dd.MM HH:mm"))
        self.link_label.setText(_translate("Dialog", "Ссылка"))
        self.ok_btn.setText(_translate("Dialog", "Готово"))
        self.open_link_btn.setText(_translate("Dialog", "Открыть ссылку"))
        self.cancel_btn.setText(_translate("Dialog", "Отмена"))
from Sources.redefined_widgets import TitleBar
